-- Run this in your Supabase SQL Editor:

-- 1. Table for Trades (already created previously)
CREATE TABLE IF NOT EXISTS trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  date DATE NOT NULL,
  pair TEXT NOT NULL,
  type TEXT NOT NULL,
  lots NUMERIC NOT NULL,
  pnl_cent NUMERIC NOT NULL,
  notes TEXT
);

-- 2. Table for Settings (to store initial balance)
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Initialize initial_balance if not exists
INSERT INTO settings (key, value) 
VALUES ('initial_balance', '500000')
ON CONFLICT (key) DO NOTHING;
