-- Run this in your Supabase SQL Editor:

-- 1. Table for Trades
CREATE TABLE IF NOT EXISTS trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  date DATE NOT NULL,
  pair TEXT NOT NULL,
  type TEXT NOT NULL,
  lots NUMERIC NOT NULL,
  pnl_cent NUMERIC NOT NULL,
  notes TEXT
);

-- 2. Table for Settings (Initial Balance, Monthly Target)
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT NOT NULL
);

-- Insert default values for settings if they don't exist
INSERT INTO settings (key, value) VALUES ('initial_balance', '500000') ON CONFLICT (key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('monthly_target', '10000') ON CONFLICT (key) DO NOTHING;

