-- Run this in your Supabase SQL Editor:

CREATE TABLE trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  date DATE NOT NULL,
  pair TEXT NOT NULL,
  type TEXT NOT NULL,
  lots NUMERIC NOT NULL,
  pnl_cent NUMERIC NOT NULL,
  notes TEXT
);

-- Enable RLS (Optional, for now you can keep it open if testing)
-- ALTER TABLE trades ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow public access" ON trades FOR ALL USING (true);
